### ISSUE TITLE
Couldnt find demonstration video

### ISSUE THREAD

**Issue by wimmatthijs** [earlephilhower/psychoclock#1]
Building somehting neat for my daughter with the ESP8266Audio library and looking for inspiration.
So i was reading in the examples and the psychoclock sounds really cool, would love to see it in action haha (if still up and running its been a while i see)

greetings from Belgium

Wim

**Comment by earlephilhower** [comment]
Sorry, but the clock only lasted about 6 months before my own kids turned it into scrap.  Instead of 3d printed PLA, I really should have made it from one of those SLM laser metal printers. 😆 

Actually, I see that I neglected to upload the STLs, mybad.  I have no idea where/if they still exist, sorry. 

Best of luck (and check it still compiles...6 years is a long time)!
